VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "DynamicControls"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Attribute VB_Ext_KEY = "SavedWithClassBuilder6" ,"Yes"
Attribute VB_Ext_KEY = "Top_Level" ,"Yes"
Public WithEvents FT_Background As Image
Attribute FT_Background.VB_VarHelpID = -1
Public WithEvents WB_Horizontal_Bar_Top As Image
Attribute WB_Horizontal_Bar_Top.VB_VarHelpID = -1
Public WithEvents WB_Vertical_Bar_Left As Image
Attribute WB_Vertical_Bar_Left.VB_VarHelpID = -1
Public WithEvents WB_Horizontal_Bar_Bottom As Image
Attribute WB_Horizontal_Bar_Bottom.VB_VarHelpID = -1
Public WithEvents WB_Vertical_Bar_Right As Image
Attribute WB_Vertical_Bar_Right.VB_VarHelpID = -1
Public WithEvents WB_Bottom_Corner As Image
Attribute WB_Bottom_Corner.VB_VarHelpID = -1




